### ISSUE TITLE
Parallel validation miss

### ISSUE THREAD

**Issue by csarofeen** [csarofeen/pytorch#1061]
```.cpp
  Fusion fusion;
  FusionGuard fg(&fusion);

  int w = 3, x = 4, y = 7, z = 8;
  auto options = at::TensorOptions().dtype(at::kFloat).device(at::kCUDA, 0);

  auto tv0 = makeSymbolicTensor(4);
  auto tv1 = makeSymbolicTensor(1);
  fusion.addInput(tv0);
  fusion.addInput(tv1);

  auto tv2 = add(tv1, new Double(1.0));
  auto tv3 = broadcast(tv2, {true, false, true, true});
  auto tv4 = add(tv3, tv0);

  fusion.addOutput(tv4);

  tv4->merge(0);
  tv4->merge(1);

  tv4->split(1, 32);
  tv4->split(0, 1);

  tv4->reorder({{2, 1}});

  tv2->computeAt(tv4, 3);

  tv4->axis(0)->parallelize(ParallelType::BIDx);
  tv4->axis(1)->parallelize(ParallelType::BIDy);
  tv4->axis(-1)->parallelize(ParallelType::TIDx);

  tv2->axis(-1)->parallelize(ParallelType::TIDx);
  tv3->axis(-1)->parallelize(ParallelType::TIDx);
```
`tv2` has the wrong parallelization, but it doesn't get caught, possibly because it's being bound to an extent of size 1 so maybe it thinks this is a broadcast dimension.

**Comment by naoyam** [comment]
At the time of validation, `tv3` is:

```
iblockIdx.x21{( ceilDiv(( 1 * i9 ), 1) )} bblockIdx.y24{( ceilDiv(( 1 * 1 ), 32) )} ithreadIdx.x22{1} bthreadIdx.x25{32}
```

And since `tv2->axis(-1)` matches with `ithreadIdx.x22{1}` of `tv3`, and they have the same threading, the validation couldn't find anything for the axis. The real problem is that `tv3` has two axes using `TIDx`, one is initially set in the fusion and another set during the time to build the CA parallel map.

In #1062, I extended the parallel validation to detect multiple uses of ParallelTypes.
