### ISSUE TITLE
Reference tensor parallelized incorrectly

### ISSUE THREAD

**Issue by naoyam** [csarofeen/pytorch#1099]
It seems after #1090 reference tensors are not parallelized correctly, which affects extent settings (https://github.com/csarofeen/pytorch/blob/20_12_3_devel/torch/csrc/jit/codegen/cuda/index_compute.cpp#L702-L704).

A bit convoluted example:

```
TEST(NVFuserTest, TMP) {
  Fusion fusion;
  FusionGuard fg(&fusion);

  auto tv0 = makeSymbolicTensor(1);
  fusion.addInput(tv0);

  auto tv1 = add(tv0, new Double(1));
  auto tv2 = add(tv1, new Double(1));
  fusion.addOutput(tv2);

  auto tv3 = makeSymbolicTensor(1);
  fusion.addInput(tv3);

  // Just to make TIDx/y/z non-exact
  auto tv4 = add(tv3, new Double(1));
  auto tv5 = add(tv4, new Double(1));
  auto tv6 = add(tv5, new Double(1));
  fusion.addOutput(tv6);

  tv2->split(0, 4);
  tv0->computeAt(tv2, 1);

  tv0->axis(-1)->parallelize(ParallelType::TIDx);
  tv1->axis(-1)->parallelize(ParallelType::TIDy);
  tv2->axis(-1)->parallelize(ParallelType::TIDz);
  tv2->axis(0)->parallelize(ParallelType::BIDx);

  tv1->setMemoryType(MemoryType::Shared);

  tv4->split(0, 5);
  tv4->axis(-1)->parallelize(ParallelType::TIDx);
  tv4->setMemoryType(MemoryType::Shared);
  tv5->split(0, 6);
  tv5->axis(-1)->parallelize(ParallelType::TIDy);
  tv5->setMemoryType(MemoryType::Shared);
  tv6->split(0, 7);
  tv6->axis(-1)->parallelize(ParallelType::TIDz);

  fusion.printMath();
  fusion.printKernel();

  FusionExecutor fe;
  fe.compileFusion(&fusion);

  auto options = at::TensorOptions().dtype(at::kFloat).device(at::kCUDA, 0);
  at::Tensor t0 = at::randn({17}, options);
  at::Tensor t3 = at::randn({19}, options);
  std::vector<IValue> aten_inputs = {t0, t3};
  auto outputs = fe.runFusion(aten_inputs);

  auto ref_t2 = t0 + 2;
  auto ref_t3 = t3 + 3;

  testValidate(
      &fusion, outputs, aten_inputs, {ref_t2, ref_t3}, __LINE__, __FILE__);
}
```
```
Inputs:
  T0_g[ iS11{( ceilDiv(i1, 4) )}, ithreadIdx.x12{4} ], float
  T3_g[ iS3{i7} ], float
Outputs:
  T2_g[ iblockIdx.x7{( ceilDiv(i1, 4) )}, ithreadIdx.z8{4} ] produce_pos( 1), float
  T6_g[ iS17{( ceilDiv(i7, 7) )}, ithreadIdx.z18{7} ], float

%kernel_math {
T1_s[ iS9{( ceilDiv(i1, 4) )}, ithreadIdx.y10{4} ] ca_pos( 1 )
   = T0_g[ iS11{( ceilDiv(i1, 4) )}, ithreadIdx.x12{4} ]
   + double(1);
T2_g[ iblockIdx.x7{( ceilDiv(i1, 4) )}, ithreadIdx.z8{4} ] produce_pos( 1)
   = T1_s[ iS9{( ceilDiv(i1, 4) )}, ithreadIdx.y10{4} ] ca_pos( 1 )
   + double(1);
T4_s[ iS13{( ceilDiv(i7, 5) )}, ithreadIdx.x14{5} ]
   = T3_g[ iS3{i7} ]
   + double(1);
T5_s[ iS15{( ceilDiv(i7, 6) )}, ithreadIdx.y16{6} ]
   = T4_s[ iS13{( ceilDiv(i7, 5) )}, ithreadIdx.x14{5} ]
   + double(1);
T6_g[ iS17{( ceilDiv(i7, 7) )}, ithreadIdx.z18{7} ]
   = T5_s[ iS15{( ceilDiv(i7, 6) )}, ithreadIdx.y16{6} ]
   + double(1);
}
```

`t4/t5/t6` are just to make `TIDx/y/z` non-exact. The point in this example is:

```
  if ((((((nvfuser_index_t)blockIdx.x) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.y)) < T0.size[0])) {
    T1[((nvfuser_index_t)threadIdx.y)]
      = T0[(((((nvfuser_index_t)blockIdx.x) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.y)) * T0.stride[0])]
      + (float) 1;
  }
  __barrier_sync(0);
  if ((((((nvfuser_index_t)blockIdx.x) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.z)) < T0.size[0])) {
    T2[(((((nvfuser_index_t)blockIdx.x) * ((nvfuser_index_t)blockDim.z)) + ((nvfuser_index_t)threadIdx.z)) * 1)]
      = T1[((nvfuser_index_t)threadIdx.z)]
      + (float) 1;
  }
```
Notice that `blockDim.x` is used as an extent of the second axis when generating the predicates. That seems because a reference tensor is created as something like `[ iS56{( ceilDiv(i1, 4) )}, ithreadIdx.x57{4} ]`, i.e., the second axis is parallelized with `TIDx`. 

This isn't an issue when generating non-predicate indices as the final index expr is generated with a producer or consumer but not a reference tensor.

It seems that the parallelization when creating a reference tensor has a problem. It uses the parallel type of a concrete domain picked from the index map, which can be different from the parallel type of the corresponding loop.

**Comment by csarofeen** [comment]
Couple things related to this... 

This conditional could just be removed, it doesn't seem like this needs to be restricted to vectorization for any reason:
https://github.com/csarofeen/pytorch/blob/20_12_3_devel/torch/csrc/jit/codegen/cuda/index_reference_replay.cpp#L210

Similarly we can parallelize producers as reference without limitation on vectorization:
https://github.com/csarofeen/pytorch/blob/20_12_3_devel/torch/csrc/jit/codegen/cuda/index_compute.cpp#L1210
and
https://github.com/csarofeen/pytorch/blob/20_12_3_devel/torch/csrc/jit/codegen/cuda/index_compute.cpp#L1210
(Still need to keep the backup parallelization to reset)

There's one more lingering, annoying issue. At this point we will be getting:
```
  if ((((((nvfuser_index_t)blockIdx.x) * ((nvfuser_index_t)blockDim.y)) + ((nvfuser_index_t)threadIdx.y)) < T0.size[0])) {
    T1[((nvfuser_index_t)threadIdx.y)]
      = T0[(((((nvfuser_index_t)blockIdx.x) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.y)) * T0.stride[0])]
      + (float) 1;
  }
```
So the predicate is now content, but indexing into T0 is off. This is actually because of the kernel ir lowering process. As we can re-parallelize fusion IR temporarily, when we lower it, specifically: 
https://github.com/csarofeen/pytorch/blob/20_12_3_devel/torch/csrc/jit/codegen/cuda/index_compute.cpp#L296-L298

We lose the parallelization on the producer id, therefore losing the extent of `blockDim.y` instead of `blockDim.x`. The only "fix" I can think of is to convert this map to be on the fusion ir, or to directly use the fusion `IterDomain::extent()` in the map, so the map is based on pure values, not on `Kir::IterDomain`.
