### ISSUE TITLE
[1.0 Requirement] Refactor graph caching

### ISSUE THREAD

**Issue by csarofeen** [csarofeen/pytorch#191]
We need to refactor/rewrite the graph caching logic. We will be implementing a 2 stage graph cache system. One that is based on fusion when contiguity, type, or device changes. The second is related to heuristics.

This first graph cache system should be pretty straight forward to reimplement but I'd like to think this back through based on the overall system, and make sure there's a clear reuse, and separation with the heuristic caching logic.

**Comment by jjsjann123** [comment]
log progress:

Things we want to cache on for graphs are `contiguity`, `type` & `device`.

We currently implement graph caching using hash on serialized/stringified graph; This naturally applies caching on `type` (as type is part of the serialized graph). The structure looks like:

    `unordered_map<string, int> graph_cache_` caching from graph to kernel_id
    `unordered_map<int, FusionExecutor*> kernel_cache_` caching from kernel_id to kerne

Where we store both `graph` & `kernel_id` as properties `attr::Subgraph` & `attr::cache_id` in `CudaFusionGroup` node. This allow us to:
1. directly fetch kernel/executor at run-time;
2. re-use compiled kernel for identical `graph`;

We can try to do the same for `device` & `contiguity`. via embedding these information when we fuse the graph (convert the subgraph to Fusion) and we cache the graph entry as a key and use that key to search generated kernel. This only solves the problem for profiling executor, which has contiguity information at compile time, during when we construct the `CudaFusionGroup` node.

For legacy executor, we need to implement another set of caching logic at run-time, since the contiguity information is not available at compile time and could vary at run-time (Note-to-myself, `device` is not that reliable for legacy executor). The extra caching logic could mean higher overhead (assert on stride_ & contiguity_) and divergent code (more of an annoyance).

We can have an extra layer of cache between serialized graph to kernel_id, or we could do this in 
`vector<vector<TensorTypePtr>, int>`. This approach does blur the boundary between graph caching & heuristic caching #192 in some sense, as we do not necessarily need to recompile when contiguity information changes (or maybe we do?).

**Comment by jjsjann123** [comment]
First PR is merged: https://github.com/csarofeen/pytorch/pull/261
Second PR under review: https://github.com/csarofeen/pytorch/pull/275
