### ISSUE TITLE
Broadcast domains used with concrete domains with different sizes

### ISSUE THREAD

**Issue by naoyam** [csarofeen/pytorch#446]
## 🐛 Bug

Broadcast domains should be able to use tensors with different sizes, but currently such fusions don't seem to work. See #445 as an example

**Comment by csarofeen** [comment]
Seems the issue is computeAt, as it should be able to detect that the program:
```.cpp
  auto tv0 = makeDummyTensor(1);
  auto tv1 = makeDummyTensor(2);
  auto tv2 = makeDummyTensor(2);
  fusion.addInput(tv0);
  fusion.addInput(tv1);
  fusion.addInput(tv2);

  auto tv3 = broadcast(tv0, {false, true});
  auto tv4 = add(tv3, tv1);
  auto tv5 = add(tv3, tv2);

  fusion.addOutput(tv4);
  fusion.addOutput(tv5);

  tv3->computeAt(tv4, -1);
```
Is invalid, as we clearly can't inline two axes that aren't provably the same size. I assume your new mapping approach will detect that these are not mappable and will not try to computeAt them in eachother. In that case we would effectively have `tv3->computeAt(tv4, 1);` which produces a correct result.

**Comment by csarofeen** [comment]
Didn't meant to close, sorry.
